### ISSUE TITLE
System.import()

### ISSUE THREAD

**Issue by Chyzwar** [leebenson/babel-preset-node7#2]
Should You also include trasform for System.import()?
https://github.com/thgreasi/babel-plugin-system-import-transformer

**Comment by leebenson** [comment]
Is there any good reason to use a polyfill vs. a library [like this](https://github.com/systemjs/systemjs)?

**Comment by Chyzwar** [comment]
systemjs is much larger thing, it is intended to work in browser and node. Since modules are part of es2015 spec babel-preset like this should provide transformation. 

IMO You should either add this missing transformation or mention in readme as limitation and recommend systemjs or polyfil.

**Comment by leebenson** [comment]
Ok, point taken. Please create a PR with it in and I will accept.
